name: apk
on: push
jobs:
  Run:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set Up JDK 8
      uses: actions/setup-java@v3
      with:
        java-version: '8'
        distribution: 'temurin'
        cache: gradle

    - name: Grant Permission for Gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew clean assembleDebug
    - name: Upload Android Build
      uses: actions/upload-artifact@v3
      with:
        name: app-debug-zipped
        path: app/build/outputs/apk/debug/app-debug.apk
